experiment_name: 'medical_img_stage1_unimodal_text_reconstruction_train'

lightning:
  trainer:
    devices: -1
    max_epochs: 10
    lr: 1e-3
    precision: 16
  checkpoint_callback:
    monitor: 'val/rougeL'
    dirpath: '/pasteur/u/esui/data/c3/medclip_ckpt'
    save_last: true
    mode: 'max'
    save_top_k: 1
  logger:
    logger_type: 'WandbLogger'
    save_dir: '/pasteur/u/esui/data/logger/'
    name: 'c3'
    project: 'c3'

encoder:
    modality: 'language' # 'language', 'both'
    embed_dim: 512

decoder:
    # Decode to language
    modality: 'language'
    model: 'gpt2'


model: 
  num_layers: 8
  mapping_type: 'mlp'
  prefix_length: 10
  clip_size: 10
  normalize_prefix: False
  is_rn: False
  gpt2_type: 'gpt2'

data: 
  dataset: 'medical'
  seed: 1234
  train_split: 'train'
  # train_data_path: '/pasteur/u/esui/data/c3/data_medclip_10k_train.pkl'
  # val_data_path: '/pasteur/u/esui/data/c3/data_medclip_10k_val.pkl'
  # test_data_path: '/pasteur/u/esui/data/c3/data_medclip_10k_test.pkl'
  # out_dir: '/pasteur/u/esui/data/c3/clip_prefix_medclip_ckpts'
  train_data_path: '/pasteur/u/esui/data/c3/data_medclip_no_aug_10k_train.pkl'
  val_data_path: '/pasteur/u/esui/data/c3/data_medclip_no_aug_10k_val_test.pkl'
  test_data_path: '/pasteur/u/esui/data/c3/data_medclip_no_aug_10k_val_test.pkl'
  out_dir: '/pasteur/u/esui/data/c3/clip_prefix_medclip_no_aug_ckpts'
  # train_data_path: '/pasteur/u/esui/data/c3/data_convirt_10k_train.pkl'
  # val_data_path: '/pasteur/u/esui/data/c3/data_convirt_10k_val.pkl'
  # test_data_path: '/pasteur/u/esui/data/c3/data_convirt_10k_test.pkl'
  # out_dir: '/pasteur/u/esui/data/c3/clip_prefix_convirt_ckpts'
    
train: 
  batch_size: 64
  num_workers: 8
  loss_fn: 
    name: 'ce_caption_loss'
  optimizer: 
    name: 'AdamW'

