experiment_name: 'clip_prefix_cap_refactored'

lightning:
  trainer:
    gpus: 1
    #distributed_backend: 'ddp'
    max_epochs: 10
    lr: 2e-5
    precision: 16
    auto_lr_find: false
  checkpoint_callback:
    monitor: 'val_loss_epoch'
    dirpath: '/pasteur/u/esui/data/coco/gpt2_finetune_ckpts'
    save_last: true
    mode: 'min'
    save_top_k: 3
  early_stopping_callback:
    monitor: 'val_loss_epoch'
    min_delta: 0.00
    patience: 10
    verbose: False
    mode: 'min'
  logger:
    logger_type: 'WandbLogger'
    save_dir: '/pasteur/u/esui/data/logger/'
    name: 'clip_prefix_cap_coco'
    project: 'clip_prefix_cap_coco'

encoder:
    clip_model_type: 'ViT-B/32'
    modality: 'vision' # 'language', 'both'
    embed_dim: 512


decoder:
    # Decode to language (ignored if modality is image)
    modality: 'language'
    model: 'gpt2'
    
    # Decode to image (ignored if modality is language)
    embed_dim: 512
    num_heads: 16
    mlp_ratio: 4.
    depth: 8
    patch_size: 16
    in_chans: 3
    img_size: 224
    checkpoint: '/pasteur/u/esui/data/ckpt/mae_visualize_vit_base.pth'


model: 
  num_layers: 8
  mapping_type: 'mlp'
  prefix_length: 10
  clip_size: 10
  normalize_prefix: False
  is_rn: False
  gpt2_type: 'gpt2'
  checkpoint: '/pasteur/u/esui/data/ckpt/semi-supervised-CLIP-generation/pretrained_models/model_weights.pt'

data: 
  dataset: 'coco'
  train_split: 'train+restval'
  train_restval_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_train+restval.pkl'
  train_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_train.pkl'
  val_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_val.pkl'
  restval_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_restval.pkl'
  test_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_test.pkl'
  out_dir: '/pasteur/u/esui/data/coco/clip_prefix_cap_refactored_ckpts'
    
train: 
  batch_size: 40
  num_workers: 8
  loss_fn: 
    name: 'ce_caption_loss'
  optimizer: 
    name: 'AdamW'
  scheduler:
    name: 'linear_schedule_with_warmup'
    warmup_steps: 5000

